pages:
      image: node:latest
        stage: deploy
          script:
              - yarn
                  - yarn build --base-href /hackerthon/ --prod
                      - mkdir public
                          - cp -r ./dist/slidingGame/* ./public
                              - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
                                artifacts:
                                    paths:
                                          - public # artifact path must be /public for GitLab Pages to pick it up
                                            only:
                                                - master 
                                                